### ISSUE TITLE
about win32 audio...

### ISSUE THREAD

**Issue by sappho192** [WenhaiLin/cocos2d-x#5]
Hi, I'm who want to play ogg files in win32 cocos2d project.
I found you are now adding some features playing ogg files on recent cocos2dx.
So I downloaded newest cocos2dx branch on Github and made new project, but it emits some errors regard of AL and GL.

Is there any way to imply your new files on cocos/audio/win32 on my project? My project is based on cocos2d-x 3.3 rc0 and now updating on [here](https://github.com/sappho192/neuBMS). I desperately want to play ogg file in win32...

**Comment by WenhaiLin** [comment]
@sappho192 Do you execute download-deps.py to download dependencies? I done it at https://github.com/cocos2d/cocos2d-x/pull/8200 and https://github.com/cocos2d/cocos2d-x/pull/8820

**Comment by sappho192** [comment]
Wow! Thanks a lot! Now I can play it.

by the way, does this experimental thing have audio delay?

**Comment by WenhaiLin** [comment]
I'm busy with another task,so i can not implement it on all platforms in v3.3.
